packages:
  - admin-panel
  - backend
  - zhangshang-shuati-app
  - shared/api

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - core-js
  - cypress
  - esbuild
  - sqlite3
  - vue-demi
  - vue-echarts
  - yorkie
